### ISSUE TITLE
Fontconfig error

### ISSUE THREAD

**Issue by systats** [openanalytics/poissontris#1]
Hey guys,

i get an error message from your beautiful package. 

"Listening on http://127.0.0.1:4394
Warnung: Error in match_family_: Fontconfig error: unable to match font pattern
Stack trace (innermost first):
    45: <Anonymous>
    44: stop
    43: match_family_
    42: FUN
    41: lapply
    40: validate_aliases
    39: svgstring
    38: server [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/poissontris/ui/server.R#286]
     2: runApp
     1: runPoissontris
Error in match_family_(font, bold, italic) : 
  Fontconfig error: unable to match font pattern
Warnung: Error in match_family_: Fontconfig error: unable to match font pattern
Stack trace (innermost first):
    47: <Anonymous>
    46: stop
    45: match_family_
    44: FUN
    43: lapply
    42: validate_aliases
    41: svgstring
    40: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/poissontris/ui/server.R#193]
     2: runApp
     1: runPoissontris
Warnung: Error in match_family_: Fontconfig error: unable to match font pattern
Stack trace (innermost first):
    38: <Anonymous>
    37: stop
    36: match_family_
    35: FUN
    34: lapply
    33: validate_aliases
    32: svgstring
    31: observerFunc [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/poissontris/ui/server.R#235]
     2: runApp
     1: runPoissontris
Warnung: Error in match_family_: Fontconfig error: unable to match font pattern
Stack trace (innermost first):
    38: <Anonymous>
    37: stop
    36: match_family_
    35: FUN
    34: lapply
    33: validate_aliases
    32: svgstring
    31: observerFunc [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/poissontris/ui/server.R#254]
     2: runApp
     1: runPoissontris
ERROR: [on_request_read] connection reset by peer
Warnung: Error in match_family_: Fontconfig error: unable to match font pattern
Stack trace (innermost first):
    47: <Anonymous>
    46: stop
    45: match_family_
    44: FUN
    43: lapply
    42: validate_aliases
    41: svgstring
    40: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/poissontris/ui/server.R#193]
     2: runApp
     1: runPoissontris
ERROR: [on_request_read] connection reset by peer"

my specs:
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Thanks for reviewing.
Greetz and thank in advance
Simon

**Comment by jlwaddell** [comment]
Hey Simon, 

Thanks for your message. From what I can tell (this may be wrong), the error appears to happen whenever there is a plot with font=2 called. This is the bold font in base R. 

I found a Google groups message discussing this same Mac error: https://groups.google.com/forum/#!topic/reporters-package/9WP5uqP2hr8

Can you let me know if the solutions there work?

Regards,
Jason

**Comment by systats** [comment]
Works perfectly fine. Thank you!
